### ISSUE TITLE
uncancer the fusion mounting points for the bends.

### ISSUE THREAD

**Issue by BadM0dder** [StarCoreSE/SCModRepository#1006]
the 90 degree curve mountingpoints suck, whenever i am trying to build with them they keep detaching themselves from eachother

![image](https://github.com/StarCoreSE/SCModRepository/assets/109397107/a18197a2-9222-4cc4-95d4-2012a7a27e3b)
It wasnt until i tried to put the side wall down that I realized it wasnt all connected.  this is actually a picture of 5 disconnected grids!  very cool.  hate.  each time I try to work on it to bend a pipe a different way it crumbles to dust and a series of confused copy and paste must be done to fix it. thank god for klimes copy paste mod.

**Comment by Jnick-24** [comment]
was intentional but fiiine, I can see how that is annoying more than anything
