### ISSUE TITLE
[40$(done)+20$] ShareTrack Refactor/SC Universal Gamemode Mod

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#1135]
Sharetrack: https://docs.google.com/document/d/1d5pZu-CSbgk_2U6wdP3t_zg7nrMbaJZGD_dVvqrK1os/
partially completed in #67

SC UGM: https://docs.google.com/document/d/1cYM0Pj6wbW64Fb55px_OLdiOkuo6zKjbBqC41HKhLJ4/

**Comment by InvalidArgument3** [comment]
refactor done in #1139

**Comment by Jnick-24** [comment]
SUGMA partially completed in #1212

**Comment by InvalidArgument3** [comment]
we are SO back
