### ISSUE TITLE
Nova cannons cant sequence fire

### ISSUE THREAD

**Issue by MaxTheFlyingCat** [StarCoreSE/SCModRepository#1186]
**Description:**
Nova cannons refuse to fire when a "Weapon group id" and "Weapon Sequence id" is set, not matter the ammount of nova cannons on in the group/ship

**Steps to reproduce:**
- Place a Nova cannon
- (Activete WC Advanced Features in the K menu)
- Give the it a "Weapon Group id"
- Give it a "Weapon Sequence id"s
- Try and fire it

**Expected behavior:**
The Nova cannon still fires and i can sequence fire with multiple in the same weapon group

**Where did the issue occur?**
- Offline Singleplayer
- Multiplayer (Combat 1)

**Comment by MaxTheFlyingCat** [comment]
@Darth411

**Comment by InvalidArgument3** [comment]
yeah anything with a burst just can't be sequenced it seems
[x] accept death
