### ISSUE TITLE
New Mod Idea: Starcore Specific Loading Screen Tips

### ISSUE THREAD

**Issue by BadM0dder** [StarCoreSE/SCModRepository#1199]
Someone who knows how to code, could you make a starcore loading screen tips mod?  Replacing the keen generic loading tips with our own semi useful ones.  I'm sure we as a community can think of a few dozen helpful things to know.

It should also be made in a way where it is easy to add or remove tips via github.

A bonus idea would be to replace keen loading screen images.  I have 3 or 4 to add if that is possible.  Cool edited stills of ships fighting would be neat.

**Comment by BadM0dder** [comment]
![Untitled6_20240530133525](https://github.com/StarCoreSE/SCModRepository/assets/109397107/f51567f2-cb7d-45e4-adc3-30264242a2b8)

**Comment by BadM0dder** [comment]
![Untitled6_20240530135002](https://github.com/StarCoreSE/SCModRepository/assets/109397107/ca67ad65-4d5c-445f-ba49-7d0c6bca1e62)

**Comment by Jnick-24** [comment]
Not possible without a plugin or client edit BUT I've got an idea for this
