### ISSUE TITLE
LB-X Causes lags/Stutter and deals to much Damage

### ISSUE THREAD

**Issue by MaxTheFlyingCat** [StarCoreSE/SCModRepository#1204]
Everything in this Issue is based on a Tank 1v1 test fight between me and Personzz were he used 4x LB-X. More test data is probably needed, but considering this was a tank vs tank fight and we are talking about an anti-tank weapon it shows that there is at least something wrong that needs to be investigated.

## Lags
Gettig hit my 4 LB-X at the same time (probably HE ammo) makes the game lag/stutter for all involved. 
I recommend a reduction of the gridlimit or revision of how damage is applied by it.

## Balance

Below you can see the Damage stats of the testfight, maybe the LB-X shouldnt outdame other anti-tank weapons by 3-4 times per BP (the chart is Damage per Battlepoint). Sure i had a ship that was basically the perfect target for LB-X with a two very flat sides, that still doesnt validate such a damage difference. 
I recomend a Damage nerf by half or BP increase fo roughly 100%.

![image](https://github.com/StarCoreSE/SCModRepository/assets/142481872/5a3c3bf3-ef50-4b80-a9a0-8445089c7fe9)

**Comment by InvalidArgument3** [comment]
cauterized in #1205
