### ISSUE TITLE
Fletcher Torpedoes not triggering WC radar missile warning

### ISSUE THREAD

**Issue by BadM0dder** [StarCoreSE/SCModRepository#1271]
Squid and I both have the issue that they do not trigger a radar warning, don't trigger RWRs, don't have little wcradar boxes around them, and also they dont get shot at by PD. 🫠

They have 200hp in the files, just checked.  All other torpedoes from other mods work fine.  Puzzling.

**Comment by TaitKaito** [comment]
Push pending: fixed by making the launch stage smart

**Comment by TaitKaito** [comment]
This has now been fixed
