### ISSUE TITLE
Extreme Shipwreck Damage

### ISSUE THREAD

**Issue by Jnick-24** [StarCoreSE/SCModRepository#1317]
yeah yeah SItanks were a bit strong but tearing one apart in literally 5 minutes is a bit absurd imo. nerf maybe?

**Comment by BadM0dder** [comment]
Did nobody push my patch?

**Comment by BadM0dder** [comment]
That's on staff smh

**Comment by Jnick-24** [comment]
what patch

**Comment by Jnick-24** [comment]
![image](https://github.com/StarCoreSE/SCModRepository/assets/94058548/af75149b-7b61-4d46-a0cf-48fbe8ef6d8f)
?

**Comment by Jnick-24** [comment]
seems to have applied, needs moar nerf :pray:

**Comment by BadM0dder** [comment]
Ok so.itnwash pushed

**Comment by BadM0dder** [comment]
And how many carronades?

**Comment by Jnick-24** [comment]
straight up doubled dmg/pt over anything else
![image](https://github.com/StarCoreSE/SCModRepository/assets/94058548/9034b0a8-b9af-48dc-8dc5-e8682187e73a)

**Comment by BadM0dder** [comment]
Heh do I need to nerf x4?

**Comment by BadM0dder** [comment]
Carronades 2km x4 is 7km

**Comment by InvalidArgument3** [comment]
slapped in #1309
