### ISSUE TITLE
Request: Claw Back Lost Performance 

### ISSUE THREAD

**Issue by BadM0dder** [StarCoreSE/SCModRepository#1426]
Where is muzzled the performance guru who made the game run smoother than butter 🧈

Eventually we will find out where the performance has gone and bring the performance back.  Watching old vods of amazing gameplay with full servers, and we still have lag stutters when we do 5v5s. 😓

This will probably be an ongoing process.

**Comment by InvalidArgument3** [comment]
new clientside performance report card just dropped
![image](https://github.com/user-attachments/assets/fd97beb0-aba8-413c-8408-4b9527cdacf7)

**Comment by InvalidArgument3** [comment]
PerfView looks like it can be a free alternative to dottrace it just has a UI from 1995 and will need a wiki article on how to use
https://github.com/microsoft/perfview

**Comment by InvalidArgument3** [comment]
"torch monitor" plugin on torch might be the profiler we need I had no idea this existed 
it exports into an external chromium thing

![163680754-1e0c0780-df62-4526-9c1f-95276d77ac65](https://github.com/user-attachments/assets/c6741868-6ad0-416d-81f0-d1433cb754be)

**Comment by InvalidArgument3** [comment]
there's now a network monitor plugin, we can see exactly where clients degrade now.
