### ISSUE TITLE
[SI Gen]

### ISSUE THREAD

**Issue by CommodoreChet** [StarCoreSE/SCModRepository#1625]
**Description:**
Moving the Field Power Slider manually causes a Network Flood due to OnChanged Packets.

**Steps to reproduce:**
Move Slider Rapdily, Observe Connection Die, rapdily changing number on Toolbar. 

**Solution**
TODO
Convert Field Power to a Once-Per-Second Update Check using a NeedsUpdate flag. EntityID Update Spreading maybe?

**Comment by ari-steas** [comment]
Tentatively fixed in #1630. Can be adjusted if the new limit is insufficient.
