### ISSUE TITLE
Chet your small reactor booster doesn't work pls fix :)))))))

### ISSUE THREAD

**Issue by TrueTurnIP** [StarCoreSE/SCModRepository#164]
**Description:**
Small reactor booster applies power output boost but gets restored to just vanilla levels after a few seconds, regardless of position of the small reactors (yes ive used the right port)

**Steps to reproduce:**
place down upgrade module
place down xyz ammount of small reactors in acb orientation
use shift t to observe power output

**Expected behavior:**
Shift T will report booster power and then after a second or two will report just the vanilla values.
**Where did the issue occur?**
- Build server

**Comment by InvalidArgument3** [comment]
its actually all of the upgrade modules reverting themselves after being placed in mp. doesnt happen in sp

**Comment by CommodoreChet** [comment]
Fixed? Maybe
