### ISSUE TITLE
modpack networking report card

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#1677]
(minimized entries are 0 packets up/down)
on connection, spawning and waiting for a minute:
![image](https://github.com/user-attachments/assets/6e8d577f-e976-49dc-b040-7d0e7f93b796)

during a 5v5 ai battle for a few minutes:
![image](https://github.com/user-attachments/assets/f3e75dc4-1289-495d-b471-0c65e6e3677b)

~~the profiler plugin crashes haha need to fix it :)~~ i fixed it

**Comment by BadM0dder** [comment]
Unfortunately for you I need someone to explain these pictures to me like I'm a 5th grader

**Comment by ari-steas** [comment]
network profiler is publicly released now, closing as redundant
