### ISSUE TITLE
SCDefenseBlocks Generator

### ISSUE THREAD

**Issue by CommodoreChet** [StarCoreSE/SCModRepository#1752]
**Description:**
Sink.Update() Doesn't Trigger Properly on Dedicated Servers

Will update this issue with the rest of the broken items I find

**Comment by CommodoreChet** [comment]
HandleResistence hook into RegisterBeforeDamageHandler seems to have stopped working server-side as well, the block is completely non-functional in any state

**Comment by BadM0dder** [comment]
F

**Comment by InvalidArgument3** [comment]
it works now
