### ISSUE TITLE
mega crash any%

### ISSUE THREAD

**Issue by BadM0dder** [StarCoreSE/SCModRepository#1808]
https://cdn.discordapp.com/attachments/858856045057146902/1309010417674358876/image.png?ex=67400673&is=673eb4f3&hm=df844e6f75526bf0ed3d7c68187deeb4a1ae032e76502c0bc25d7b0ffcd0ee63&

logs:
https://discord.com/channels/855480694137946153/858856045057146902/1309010249096757398
https://discord.com/channels/855480694137946153/858856045057146902/1309010284500881429
https://discord.com/channels/855480694137946153/858856045057146902/1309010339391864923

a crash of all time. was sitting still waiting for a game to start,

**Comment by ari-steas** [comment]
finally got around to checking, sharpdx crash woo! If it were like the others I suspect we would have run into it again already, I blame cosmic rays
