### ISSUE TITLE
turretring rotors crash when certain ones try to spawn a small grid version

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#200]
fork and fix (remove ui element somehow)?

**Comment by CommodoreChet** [comment]
![image](https://github.com/StarCoreSE/SCModRepository/assets/50426713/3872cb97-ebb0-4bf7-9fa1-3f3714ef8463)
https://github.com/StarCoreSE/SCModRepository/commit/cbf85f33aae85f1ed3cb3505ba4ae3a4890de7f7

Resolved as of this commit. Added a Script that removed the Add Small Rotor Head option entirely
