### ISSUE TITLE
Small hydrogen tank restricted when it shouldn't be

### ISSUE THREAD

**Issue by MuzzMuzz** [StarCoreSE/SCModRepository#254]
**Description:**
Small Hydrogen tanks shouldn't be restricted from use.

**Steps to reproduce:**
>Place small tank
>fuck off
>wooow

**Expected behavior:**
Small Hydrogen tank placed.

**Where did the issue occur?**
- SP world.

**Comment by InvalidArgument3** [comment]
pm'd you the fix :)
