### ISSUE TITLE
mods that can't be loaded in an empty world with just WC

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#261]
- solaris hypernautics (AMP custom component dependency)

**Comment by CommodoreChet** [comment]
Solaris Hypernautics Interdependency should be resolved as of these Commits:
https://github.com/StarCoreSE/SCModRepository/commit/566d57864731cf783008c9a61ae4ae6ca2c1fa1b
https://github.com/StarCoreSE/SCModRepository/commit/413828aa06a26c61fa6b4c02d9e4f451198eb303
https://github.com/StarCoreSE/SCModRepository/commit/ddcdc753dd23d35baaa920c143c99656d825ace9
