### ISSUE TITLE
Lagment

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#309]
extreme lag. 30s-8m delay on many actions. Further information in logs channel.

Submitted by: Personzz

**Comment by InvalidArgument3** [comment]
likely made worse by #399

**Comment by Tiberias42** [comment]
Should be fixed, requires observation, will revisit after "4.0" fight night

**Comment by Jnick-24** [comment]
Is this still an issue? As far as I know, it never came up
