### ISSUE TITLE
hold F to enter breaks sometimes

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#313]
- if the target has a subgrid

Submitted by: Invalid

**Comment by InvalidArgument3** [comment]
this happens when there's a subgrid on your grid for some reason

**Comment by CommodoreChet** [comment]
Probable Solution is to just always have a Main Cockpit set. Alternatively, could modify Proximity Entry to only use the Raycast target grid, rather than the grid group?

**Comment by CommodoreChet** [comment]
Wont Fix - Set Main Cockpits when Possible, or try holding F to Enter on the Sub grid itself rather than the main grid

**Comment by InvalidArgument3** [comment]
it's ignoring main cockpits, but this is an easy fix when I can get around it

**Comment by InvalidArgument3** [comment]
#622 behavior changed

**Comment by Tiberias42** [comment]
Forgot to close this
