### ISSUE TITLE
hurricane missing sound after new model

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#323]
hurricane missing sound after new model

Submitted by: Invalid

**Comment by CommodoreChet** [comment]
Result of using a shared sound from AWE. Will be resolved in a push relatively soon

**Comment by CommodoreChet** [comment]
Resolved as of this Commit:
https://github.com/StarCoreSE/SCModRepository/commit/28c14dba2abc3a29b6ac0762c0da6c0798973310
