### ISSUE TITLE
Buster config bug

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#330]
Busters have the exact stats of a single heavy armour block. 

Submitted by: Personzz

**Comment by CommodoreChet** [comment]
![image](https://github.com/StarCoreSE/SCModRepository/assets/50426713/6d7311db-cb86-4ba2-8ef0-ad8c5501bbc3)
![image](https://github.com/StarCoreSE/SCModRepository/assets/50426713/ed78ef42-dfef-4a05-be0c-69cede24a069)

They may have the Same Integrity, but the Buster has additional resistances, a higher grind time, and no deformation
