### ISSUE TITLE
Sauron does not provide tracking for Brainless PD

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#343]
Sauron does not provide tracking for Brainless PD. Not sure if this is a bug or intended behavior.

Submitted by:

**Comment by CommodoreChet** [comment]
Cannot Replicate - Further Investigation Needed

**Comment by CommodoreChet** [comment]
Issue Replicated - Working on a Fix

**Comment by CommodoreChet** [comment]
Use RWRs instead. May fix later, but this solution is satisfactory for now,

**Comment by InvalidArgument3** [comment]
going to try out different configurations on AI targeting settings

**Comment by CommodoreChet** [comment]
fixed? maybe? someone should check
