### ISSUE TITLE
flat atmo realfakes

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#353]
Realfakes for flat atmo thrusters. Make them X*X*1 for easy placement and have a hollow collider (or none at all). This way real thrusters can pass through them and we can use them as decorative thrust covers. ~100 integrity or some such thing. These are purely decorative.

Submitted by: Personzz

**Comment by CommodoreChet** [comment]
Made into a 1x1x1, Physics set to False. Can be used Decoratively for Thruster Covers or otherwise.
https://github.com/StarCoreSE/SCModRepository/commit/a1888d6fb388f091c7c795f86626bcc936ce021b
