### ISSUE TITLE
Some realfake blocks have reverted to thier real counterparts/and or have not been carried over

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#372]
Some blocks that count towards cockpit count (such as desks) that were changed to realfake blocks have either reverted or not carried over and are counting towards the cockpit count on the stat tracker again. Also realfake NPCs have not been carried over. 

Submitted by: Spartan

**Comment by CommodoreChet** [comment]
Standalone RealFakeDoors Mod seems to be missing from the Starcore MT World
Could roll it into Season 4 Adjustments?

**Comment by InvalidArgument3** [comment]
fixed

**Comment by InvalidArgument3** [comment]
not quite fixed, old ones may need to be replaced to be re-overwritten with CubeBlock types
