### ISSUE TITLE
misc errors in the world log

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#376]
![image](https://github.com/StarCoreSE/SCModRepository/assets/51190031/aa2d88d3-3ce8-483d-8dab-acb6dbd15891)

MOD_ERROR: Starcore Basic Greebles, in file: O:\SteamLibrary\steamapps\workshop\content\244850\2897767540\Data\Replacement_Audio.sbc
3D sound 'MusCalm_02', 'O:\SteamLibrary\steamapps\workshop\content\244850\2897767540\Audio\RideOfTheValkyries.xwm' must be in mono, got 2 channels
MOD_ERROR: Anomaly-Solaris-Hypernautics, in file: O:\SteamLibrary\steamapps\workshop\content\244850\2983399274\Data\AMP_Audio.sbc
Unable to find audio file: 'MaxMemeReload', 'Audio\Krankenschwester_bereit.mp3'
[BuildInfo] If you intend on referencing game sounds, you can only do with .wav files by using original relative path and removing the .wav extension.
MOD_ERROR: [AMP] Aristeas Melee Pack, in file: O:\SteamLibrary\steamapps\workshop\content\244850\2870210922\Data\Scripts\TransparentMaterials.sbc
Resource not found, setting to null. Resource path: O:\SteamLibrary\steamapps\workshop\content\244850\2870210922\Textures\arcBeamHSF.dds
MOD_ERROR: [AMP] Aristeas Melee Pack, in file: O:\SteamLibrary\steamapps\workshop\content\244850\2870210922\Data\Scripts\TransparentMaterials.sbc
Resource not found, setting to null. Resource path: O:\SteamLibrary\steamapps\workshop\content\244850\2870210922\Textures\arcBeamHS.dds
MOD_ERROR: OnyxArmamentCo, in file: O:\SteamLibrary\steamapps\workshop\content\244850\3123483745\Data\onyx_Audio.sbc
Resource not found, setting to null. Resource path: O:\SteamLibrary\steamapps\workshop\content\244850\3123483745\Audio\Hurricane_Firesound_01.wav
[BuildInfo] Path to sounds in mods start from the mod root folder.
MOD_ERROR: OnyxArmamentCo, in file: O:\SteamLibrary\steamapps\workshop\content\244850\3123483745\Data\onyx_Audio.sbc
Resource not found, setting to null. Resource path: O:\SteamLibrary\steamapps\workshop\content\244850\3123483745\Audio\Hurricane_Firesound_01_Distant.wav
[BuildInfo] Path to sounds in mods start from the mod root folder.
mod_warning: Anomaly-Solaris-Hypernautics, in file: O:\SteamLibrary\steamapps\workshop\content\244850\2983399274\Data\AMP_Audio.sbc
File extension of: Audio\Krankenschwester_bereit.mp3 is not supported.

**Comment by CommodoreChet** [comment]
Most Errors should be resolved as of this Commit
https://github.com/StarCoreSE/SCModRepository/commit/cd56199a9d7244c19bc05fc1143c9cb2315e75e8

**Comment by CommodoreChet** [comment]
forgot some
https://github.com/StarCoreSE/SCModRepository/commit/70cfd1ac7f43aed25b812e3b0171e05b2637d9a2
