### ISSUE TITLE
Climbing cost does not work

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#378]
refer to question 1

Submitted by: turnip

**Comment by CommodoreChet** [comment]
Climbing Cost on the Chiasms and Flares doesn't appear to work. Other blocks potentially effected?

**Comment by InvalidArgument3** [comment]
climbing costs work it's just the list was slimmed down from s3 during refactoring just need to put the entries back into ShipTracker.cs in sharetrack

![image](https://github.com/StarCoreSE/SCModRepository/assets/51190031/731292c2-22a2-4c82-9d52-f5029eae4040)

**Comment by CommodoreChet** [comment]
Should be Resolved as of This Commit:
https://github.com/StarCoreSE/SCModRepository/commit/127494330db41765cd515dce0bd62231263d3882

Closing as Addressed
