### ISSUE TITLE
Hellfires only have 99k integrity

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#380]
Hellfires have much less integrity and resistance than hydras, which have a similar bp and size

Submitted by: Squid

**Comment by CommodoreChet** [comment]
Transplanted Hydra Component List into Hellfire. May need further Adjustment?
https://github.com/StarCoreSE/SCModRepository/commit/f6ae87f54566fcf7a341a5918f14b68350adea23

Closing as Addressed
