### ISSUE TITLE
CC still broken

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#382]
There are currently three weapons with working climbing cost. LRMs, MRMs, and Project Pluto. Replicable on build server

Submitted by: Personzz

**Comment by CommodoreChet** [comment]
Should be Resolved as of This Commit:
https://github.com/StarCoreSE/SCModRepository/commit/127494330db41765cd515dce0bd62231263d3882

Closing as Addressed
