### ISSUE TITLE
Paperdoll not tracking subgrids

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#392]
Paperdoll doesn't show subgirds, and it would be cool if it did.

Submitted by: Darth411

**Comment by CommodoreChet** [comment]
Paper Doll already seems to have Subgrid Support, will have to investigate why this is non-functional

**Comment by CommodoreChet** [comment]
turns out thats not actual subgrid handling, no idea what thats supposed to be doing. Going to mark this as Unsolvable currently
