### ISSUE TITLE
Shield pasting bug

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#394]
shields are significantly stronger on most grids when pasted in. To fix this, a full block of light or heavy armor must be removed and replaced on the grid. Adding blocks does not fix it, removing other blocks does not fix it [so far as I have seen]. I am not 100% sure this happens with *all* grids but certainly many as it was casually replicated by me and McTedTed today and I have observed it in many scrimmage matches the past two weeks.

Submitted by: Personzz

**Comment by InvalidArgument3** [comment]
this is likely reactor upgrades taking a second to apply, need to find a way to force shields to recalculate

**Comment by Tiberias42** [comment]
Should be solved as of pull request #412

**Comment by Tiberias42** [comment]
Damnit, I mean this commit:
https://github.com/StarCoreSE/SCModRepository/pull/412/commits/15266025dce9e34d3e0f1e7354fe61e194a1c493
