### ISSUE TITLE
Integrity Enhancer not working

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#395]
the structural integrity enhancer does nothing, tested with an identical ship except one had a 30% integ enhancer on it and the other didnt, there was no difference. Siege mode activates and then immediately turns itself off. 3/10 would not buy for 450bp.

Submitted by: turnip

**Comment by CommodoreChet** [comment]
Should be Fixed:tm: as of these commits

https://github.com/StarCoreSE/SCModRepository/commit/b968216f40de5c09981315d773ba20e18cf37f5f
https://github.com/StarCoreSE/SCModRepository/commit/e8b730350c2da9be8d8ac8303a3508865e3f301d
