### ISSUE TITLE
Adjust t44 afterburner collision box

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#404]
The current collision box for the t44 requires a 3x3 rectangle bored into the ship which leaves a big and ugly gap around it. I would be cool if it was reduced enough to allow it to be surrounded with slopes.

Submitted by: Squidopolous

**Comment by Tiberias42** [comment]
Fixed in commit:
https://github.com/StarCoreSE/SCModRepository/pull/504/commits/ee84a904597b38875723d85a52ab1f89e1ebb289

**Comment by Tiberias42** [comment]
Who's, wrong one

**Comment by CommodoreChet** [comment]
Apparently Adressed
