### ISSUE TITLE
2024-01-21 00:59:33.505 - Thread:   1 ->  Could not find any sound for 'Battleship_Cannon_Firesound_Dist3'

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#415]
being spammed in the log

Submitted by: Invalid

**Comment by CommodoreChet** [comment]
Fixed as of this commit
https://github.com/StarCoreSE/SCModRepository/commit/3af7d4ee6c4de0b56e15c27c12ca5922fefaac46
