### ISSUE TITLE
Buffed interior thrusters

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#452]
some thrusters like small hydro (vanilla, unarmored one) has a small burn length (on the single player world at least)

Submitted by: EngineRichExhaust

**Comment by Tiberias42** [comment]
It appears only to affect 1x1 & 3x3 unarmored vanilla hydrogen thrusters.  Need to check overrides for flame lengths

**Comment by Tiberias42** [comment]
Fixed in commit:
https://github.com/StarCoreSE/SCModRepository/pull/504/commits/ee84a904597b38875723d85a52ab1f89e1ebb289
