### ISSUE TITLE
Small Reactor Upgrade Module integrity is anomalously low

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#455]
lightweight (2.5k kg) and fragile (11.7k integ), whereas small reactor is almost twice as heavy and has more integ (12k integ).  Shouldnt it be the opposite, probably approaching a heavy armor block in integ.  Keep it consistent with small gyro upgrade.

Submitted by: EngineRichExhaust

**Comment by CommodoreChet** [comment]
Fixed as of this commit:
https://github.com/StarCoreSE/SCModRepository/commit/d0cc143dfe9707fe7586879631cb00c3213f9ffb
