### ISSUE TITLE
miniblink

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#462]
Currently, if there are loose blocks inside your grid it might cause you to violently jitter around making aiming guns very hard. It would be nice to have a miniblink block that will teleport your ship a very short distance forward to clear the inside of debris. Ideally it would be pretty cheap and grid limited to 1 so it's not used as a normal blink

Submitted by: Squede

**Comment by InvalidArgument3** [comment]
need to check this with a rotor on the grid vs. multiplayerpredictionswitcher affected grids. maybe there's some delay before it kicks in

**Comment by Tiberias42** [comment]
Could we develop this alongside the fix for #255?

**Comment by InvalidArgument3** [comment]
essentially done with the new custom blink
