### ISSUE TITLE
5x5 hydro burn radius is too small?

### ISSUE THREAD

**Issue by angu5tu5** [StarCoreSE/SCModRepository#512]
**Description:**
The 5x5 hydrogen thruster has the same burn damage radius as the 3x3 hydrogen thruster

**Steps to reproduce:**
shft + to look at the burn radius
![image](https://github.com/StarCoreSE/SCModRepository/assets/159586881/9d6e2209-2f03-4fb6-a571-42bd753f63ea)

![image](https://github.com/StarCoreSE/SCModRepository/assets/159586881/2bd0c2be-6f95-4daf-9105-9e89d4bafb7a)

**Expected behavior:**
Have a burn radius that matches the AWG ion thruster/burn radius that touches the side

**Where did the issue occur?**
- Combat server 1

**Comment by InvalidArgument3** [comment]
unfortunately I think this can only be edited in the .blend of the file

**Comment by Tiberias42** [comment]
> unfortunately I think this can only be edited in the .blend of the file

poop
