### ISSUE TITLE
Blocked SRB Damage

### ISSUE THREAD

**Issue by Jnick-24** [StarCoreSE/SCModRepository#517]
Placing any block directly behind an SRB or afterburner entirely stops its damage cone.

![2024-02-10-13-49-22-101](https://github.com/StarCoreSE/SCModRepository/assets/94058548/ae8d8b98-7290-40e9-b7b6-cd143b781692)

**Comment by InvalidArgument3** [comment]
gonna need to just be a frowny face rule i have no idea if this can be solved mechanically
