### ISSUE TITLE
Dev Branch

### ISSUE THREAD

**Issue by Jnick-24** [StarCoreSE/SCModRepository#584]
A development branch that auto-pushes to a separate set of mods. Allows for testing on [an actual server] without annihilating the balance/performance/stability of the main branch.

maybe a modified auto-upload script that reads a different config file?

![activation](https://github.com/StarCoreSE/SCModRepository/assets/94058548/ad2c8d61-4bf8-4a37-963f-19d40d1a36f3)

**Comment by CommodoreChet** [comment]
Perhaps move the Dev folders into their own branch/repository?

**Comment by Jnick-24** [comment]
Yeah, having dev versions inside the main repo kinda clutters it up a lot (and makes pushing dev to main a bit more challenging)

**Comment by InvalidArgument3** [comment]
branches are weird with how we have things set up; an SCModRepository-Dev would cut the filesize in half, that's probably what we'll do

**Comment by InvalidArgument3** [comment]
moved stuff into folders for now, will revisit in future
