### ISSUE TITLE
Erebos Restriction Radius checks from Block Center, Rather than Block Edge.

### ISSUE THREAD

**Issue by CommodoreChet** [StarCoreSE/SCModRepository#633]
The Erebos has a 5 Meter Restriction Radius, but due to its size, this isn't large enough when projected from block center to adequately prevent spam, as it only forces a 1 block gap.

**Expected behavior:**
Turn on Check Inflated Box, so the radius is projected from block edge rather than center. This would prevent ridiculous amounts of Spam, which feels pretty bad to fight against.

**Comment by InvalidArgument3** [comment]
done
