### ISSUE TITLE
Hey Nate fix the Plane Stuff:

### ISSUE THREAD

**Issue by BadM0dder** [StarCoreSE/SCModRepository#715]
You cant use invalids sounds forever, hurry up

Get the trails optimized then apply them.  Get a smoking/damaged particle for when it enters its return home stage for being shot.

Vibecheck sounds.  Vibecheck HP.

Then Make a proper reload animation for when the plane has returned and is ready to fire.  Make a cool topgun afterburner test where it revs the engine then launches off the deck.  

And make a variant with flat blastdoors and not the edge one, same stats just different mounting model.

Maybe try advanced drone system too.

And add the ... fuck brain nooo.  ok future nate pls think of what past nate was thinking about before present nate forgot, then add that here.

-Nate

**Comment by InvalidArgument3** [comment]
it's probably fine
