### ISSUE TITLE
Low Power replace mass with Ewar shove from center of mass.

### ISSUE THREAD

**Issue by BadM0dder** [StarCoreSE/SCModRepository#716]
Yeah that should fix most of the spinning.  Still need to keep some of the spin, but this should make it move people without making personz riot.

**Comment by Tiberias42** [comment]
Note, this should be combined with Issue #696

**Comment by Tiberias42** [comment]
After watching Ender juggle Nate with 5 LP Hunters, I think they are doing just fine.  If anything, we should make it more expensive for people to meme with a pile of LP Hunter shots.
