### ISSUE TITLE
Tie in Maximum rotational velocity to Total Mass, like speed curve.

### ISSUE THREAD

**Issue by BadM0dder** [StarCoreSE/SCModRepository#717]
The fatter you are, the slower you are to turn.  But shield bumping wont spin you as much as the smaller guy, same with hunter shots.  Rotate slower but also have less problems with being rotated.

This hopefully will fix darths problem with shield bumping look silly, as it would be the lighter grid that yields to the bumping first due to having a higher top rotational speed. (theoretically)

**Comment by Malthestion** [comment]
No--spin harder. You live by the beyblade, you die by the beyblade. Alternatively, quadruple the cost of large gyros. Make balance great again.

**Comment by Tiberias42** [comment]
Note, this should be combined with #702
