### ISSUE TITLE
small tanks

### ISSUE THREAD

**Issue by BadM0dder** [StarCoreSE/SCModRepository#718]
why are they so favored by balance team currently?

need to brainstorm as to why taking 3x3x3 block tanks might have some minor advantages over the 1x1x2 block tank.

I think dropping 3x3 tanks from 30 BP to 10 BP might be good, while also raising the small tank from 1x1x2 from 30 BP to 50 BP.
Players would then try to squeeze in the big 3x3 tanks which make big explosions when they are killed, as the battlepoint race to "more guns at all cost" means they will pick the inconvenient cheaper option every time.  People probably will have 1 small tank in a busterblock core somewhere still.  Currently most ships have 2-3 small tanks and call it a day.

**Comment by Tiberias42** [comment]
Pepperidge Farms remembers when the small tanks were restricted.

**Comment by Tiberias42** [comment]
Lets get through 4.2 & see how things go
