### ISSUE TITLE
Season Uhhhh Adjustments 

### ISSUE THREAD

**Issue by BadM0dder** [StarCoreSE/SCModRepository#722]
Somethings different, its way darker now than how it was in season 3.

Removed season 4 adjustments from single player world, it looks better (imo), which i thought was weird.

Loaded season Uhhh adjustments, a old muzz mod from who knows when, and it got rid of the vanilla "turn everything black", built a box and trapped myself inside it and it wasnt pitch black.

**Comment by BadM0dder** [comment]
added zip in logs and complaints, please see attached file.

**Comment by Malthestion** [comment]
Is that why everything turns pitch-black in single player when I go in my camera? Yeah that's annoying

**Comment by Tiberias42** [comment]
Fixed in Pull #826
