### ISSUE TITLE
Large Reactor Conveyor Broke

### ISSUE THREAD

**Issue by BadM0dder** [StarCoreSE/SCModRepository#734]
Sixty tells me that one side of his large reactor is not working as a conveyor.

Cheeeeeet pls fix

**Comment by BadM0dder** [comment]
wait it might be all the small reactors of old grids being rotated when pasted into a MT world, and so the pipe leading out from the large reactor was broken by that elsewhere.

**Comment by Tiberias42** [comment]
Unable to replicate
