### ISSUE TITLE
retractable turrets spazz out due to self repair script flipping their state when grid power is off

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#738]

**Comment by BadM0dder** [comment]
Was just about to post this haha.  It seems to happen when you still have power blocks on grid but none of them are functional.  Placing a reactor or battery seems to fix all animation errors after about 5 or so seconds

**Comment by Jnick-24** [comment]
Seems to be an issue with WeaponCore rather than SelfRepair.

**Comment by BadM0dder** [comment]
Yeah not fixable by us unless someone wants to fix the animation engine itself
