### ISSUE TITLE
Todo: blink drive intersect detection (total telefrag death)

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#759]
need to add actual detection for EntityCovers, voxels, etc. so you don't get stuck in them. Maybe add an "Unsafe" blink drive variant that doesn't care about grids.

**Comment by Jnick-24** [comment]
Fixed again with #784, fingers crossed

**Comment by BadM0dder** [comment]
all I hear are people saying there blink drives wont let them blink.  I am all for nerfing the blink drive so keep up the good work.

**Comment by Jnick-24** [comment]
Might be resolved when #863 is fixed, closing for now as 'On-Hold'
