### ISSUE TITLE
[15$] CTF Return Sphere Doesn't Show

### ISSUE THREAD

**Issue by Jnick-24** [StarCoreSE/SCModRepository#786]
The CTF flag return sphere doesn't show up in multiplayer. Hate,

**Comment by BadM0dder** [comment]
make it a smaller boundingbox to return the flag so when A team makes B team drop B flag, they need to then point at it and afterburn/fly through it to return it, like suggested in the 4.1 feedback ¯\_(ツ)_/¯

**Comment by InvalidArgument3** [comment]
upgraded to a Bounty™

**Comment by Jnick-24** [comment]
Resolved by #866
