### ISSUE TITLE
A different idea to fixing shields

### ISSUE THREAD

**Issue by BadM0dder** [StarCoreSE/SCModRepository#788]
is it possible to get the bonus of a fully shunted shield face to apply to a shield with 2 faces up? aka not punish players for having 2 shield faces up instead of just 1?  Like it could be accomplished with something as simple as moving the sliding scale of benefits of shunting left 1 space?

![image](https://github.com/StarCoreSE/SCModRepository/assets/109397107/7c1e5ca8-18d5-46d6-911d-98c198b16dd0)

Currently when you have 2 faces up your shield face dies immediately under any sustained fire, so the current meta is "hang back and present 1 face to the enemy" because having 1 face open is twice as durable as 2 open faces.  With the current weapons and alpha strike damages, you NEED that resist so it is optimal to only fly with 1 face open which means always face badguys and control the fight so they always shoot your 1 shield face.

As someone who does this, I can say its hella boring.  Having 2 faces that your able to move around means you can get in there and brawl with the enemy team while still having shields up, with your front face up and moving the 2nd face around between sides and rear as you fly through the enemy formations and brawl with people.  Brawling is exciting and fun cause there is danger from all sides.  Right now if you take shots through a shunt that can be GG depending on the weapons, so having that heathbar that you can move around means people should be more likely to brawl and have fun cause its up to you to move around the shield and be aware to which side bullets are coming from.  I hope ive explained this enough, let me know if i havent i can go into more depth in voice.

**Comment by Tiberias42** [comment]
Attempt to test idea will be post 4.2

**Comment by BadM0dder** [comment]
main problem seems to be either you out regen shield damage right now or shield faces go down too quickly.  Leading to fights where one team has taken no damage where the other team has been wiped out.  Swingy fights like those are suboptimal, idealy teams of equal quality should result in one team should dead and the other team left feeling like they won by the skin of their teeth.  Those are optimal for the players, and also the most tense/best to watch fights.
