### ISSUE TITLE
CVS WONT FILL MY MEDS

### ISSUE THREAD

**Issue by BadM0dder** [StarCoreSE/SCModRepository#855]
**Description:**
_A clear and concise description of what the bug is._
CVS WONT FILL MY MEDS

**Steps to reproduce:**
GO TO CVS

**Expected behavior:**
_A clear and concise description of what you expected to happen._
EXPECTED MEDS

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer (Private, Friends, Public world) / Offline Singleplayer
AT CVS DRIVE THROUGH

**Log Files:**
- SpaceEngineers-[numbers].log found in %Appdata%/SpaceEngineers
LOG DEZ NUTS

**Additional context:**
_Add any other context about the problem here._
I WOULD LIKE MY $370 MEDS CVS
they do this EVERY OTHER FUCKING MONTH

**Screenshots:**
![image](https://github.com/StarCoreSE/SCModRepository/assets/109397107/da72c78f-c45b-499b-9ba3-fdaedac8d992)
sEE aTTACHED sCREENSHOT

**Comment by BadM0dder** [comment]
Excellent News from CVS

**Comment by Tiberias42** [comment]
Certified *Bruh* moments
