### ISSUE TITLE
[60$] Modular Assemblies

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#890]
**Required Features**

- Core mod
- Demo mod (fusion reactor loops, whatever)
- A repository and a wiki that explains how to set up a basic addon
- A steam workshop page, when the mod is in a presentable state
- Ideally, doesn't crater performance

https://github.com/StarCoreSE/Modular-Assemblies

**Comment by Jnick-24** [comment]
https://docs.google.com/document/d/14Pa05EGb13oMFakVZCvmQfIso7seWI_B6cNXra3YeY8/edit

**Comment by InvalidArgument3** [comment]
+10$ - RichHud UI™
