### ISSUE TITLE
[10$] reproducable anomalous thread freeze

### ISSUE THREAD

**Issue by InvalidArgument3** [StarCoreSE/SCModRepository#893]
- Sometimes, for some reason, clients or the server will freeze. This usually occurs under load.

Instances of it happening:
- In TT 4.2, when two players had the flag and were flying around shooting each other
- Toggling the RCS block "off"
- Changing some settings in the terminal under some circumstance(?)
- #491 

It's extremely inconsistent and feels completely random, no crash log is left behind since the game watchdog will mercy kill the program. I need a way to trigger it

**Comment by InvalidArgument3** [comment]
Squidopolis got it immediately when he ran /start in sharetrack when the chat was being odd.

**Comment by Jnick-24** [comment]
Might be garbage collector related, got a ton of similar freezes while doing testing. Screenshots in DMs.

**Comment by InvalidArgument3** [comment]
the flag isn't real anymore will reopen if it comes back
