### ISSUE TITLE
upside down turrets are desynced

### ISSUE THREAD

**Issue by BadM0dder** [StarCoreSE/SCModRepository#907]
**Description:**

Turret fire is shown to client incorrectly

**Steps to reproduce:**

Not sure yet, watch any of squids streams when hes fighting for MCR

**Expected behavior:**
Bottom turrets should behave like top turrets, but are not

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer (Private, Friends, Public world) / Offline Singleplayer

TT4.2, squidopolis stream

**Log Files:**
- SpaceEngineers-[numbers].log found in %Appdata%/SpaceEngineers

**Additional context:**

Top electron turrets are fine. bottom 3 are fucked.  this might be a weaponcore bug.

**Screenshots:**

**Comment by BadM0dder** [comment]
Need to watch stream to see if this is still happening now

**Comment by InvalidArgument3** [comment]
will reopen this if it manifests next TT
