### ISSUE TITLE
Nova Cannon Mounting points are incorrect

### ISSUE THREAD

**Issue by MaxTheFlyingCat** [StarCoreSE/SCModRepository#940]
**Description:**
The Nova cannons mounting points are currently on the barrel instead of the base

**Steps to reproduce:**
Place blocks on the nova cannon or active the Buildinfo mode that lets you see Mountingpoints

**Expected behavior:**
Mountingpoints are on the base

**Where did the issue occur?**
Every world

**Screenshots:**
![image](https://github.com/StarCoreSE/SCModRepository/assets/142481872/88c2a202-3726-4de7-a674-2fd3379998ac)

**Comment by Darth411** [comment]
Should be fixed now
