### ISSUE TITLE
(MoA) Fusion Loops bug out after repaste when connecting multiple Mulit-feeder Fusion loops

### ISSUE THREAD

**Issue by MaxTheFlyingCat** [StarCoreSE/SCModRepository#984]
**Description:**
When connecting fusion accelerator loops who are connected to two different Feeders, the loops bug out after repaste. This can be confirmed through both !mwdebug and connection a fusion consumer.

**Steps to reproduce:**
- place four Accelerator feeders on top of each other (connected)
- place 4 Accelerator corners connection two feeders each
- use !mwdebug -> should display a fusionsystemwith 2 loops
- crtl-x, ctrl-v the grid
- use !mwdebug -> should display a fusionsystem with only 1 loop

**Expected behavior:**
Even when using multiple feeders, as long as they are connected, the ammount of fusion loops shouldnt change, especially after a repaste.

**Where did the issue occur?**
- SP
- Buildserver (didnt check the other servers)

**Screenshots:**
No interconnection (single feeder loops)
!mwdebug loops before repaste: 6, after repaste: 6
-> Works as intended (reactor output confirms)
![Single Feeder](https://github.com/StarCoreSE/SCModRepository/assets/142481872/b7e0fded-daee-44ed-8551-052e68e4872f)

Feeders connected to each other
!mwdebug loops before repaste: 6, after repaste: 4
-> Doesnt work as intended (reactor output confirms)
![Multi Feeder](https://github.com/StarCoreSE/SCModRepository/assets/142481872/9cdef319-c8f8-46a5-8a92-fce219e9c53d)

Doesnt even need pipes to connect each other
!mwdebug loops before repaste: 4, after repaste: 2
-> Doesnt work as intended (reactor output confirms)
![Multi feeder simplyfied](https://github.com/StarCoreSE/SCModRepository/assets/142481872/310ddf93-66a7-4e89-aac1-5e2d8349cf35)

**Comment by MaxTheFlyingCat** [comment]
@Jnick-24

**Comment by Jnick-24** [comment]
#993
